# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.define "SUT" do |s|
    s.vm.hostname = "SUT"
    s.vm.network "private_network", ip: "192.168.51.3",
        virtualbox__intnet: "tu2sd", adapter: 2
    s.vm.network "private_network", ip: "192.168.52.3",
        virtualbox__intnet: "td2su", adapter: 3
    s.vm.network "private_network", ip: "192.168.53.3",
        virtualbox__intnet: "mgmnt", adapter: 4
    s.vm.provider "virtualbox" do |vb|
      vb.name = "SUT"
      vb.memory = 3072
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--nic1", "nat"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype3", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype4", "virtio"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
    end
    config.vm.synced_folder ".", "/vagrant"
    config.vm.synced_folder "../..", "/opt/tipsy"
    s.vm.provision "shell", path: "install.sh"
    s.vm.provision "shell", path: "start-ovs.sh", run: 'always'
  end
end
