#!/bin/sh

TIPSY=/opt/tipsy/tipsy

# Permanently add 'sut.local' to the list of known hosts
ssh -o StrictHostKeyChecking=no sut.local echo

if [ $# -gt 0 ]; then
    tests=0_default.json
    for test in $*; do
        tests="$tests ${test}.json"
    done
else
    tests="*.json $($TIPSY list-module-tests)"
fi
cd /vagrant/tests
$TIPSY config -f $tests
make
