#!/bin/sh

TIPSY=/opt/tipsy/tipsy

# Permanently add 'sut.local' to the list of known hosts
ssh -o StrictHostKeyChecking=no sut.local echo

if [ $# -gt 0 ]; then
    tests=0_default.json
    for test in $*; do
        if [ -e ${test}.json ]; then
            tests="$tests ${test}.json"
        else
            f=$(find $(dirname $TIPSY)/module -name test-${test}.json)
            if [ $(echo $f|wc -w) -eq 1 ]; then
                tests="$tests $f"
            else
                echo Cannot find: $test >&2
                exit 1
            fi
        fi
    done
else
    tests="*.json $($TIPSY list-module-tests)"
fi
cd /vagrant/tests
$TIPSY config -f $tests
make
