#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ $# -gt 0 ]; then
    # Active the given python virtual environment
    source $1/bin/activate
fi

cd "$DIR"
ryu-manager --config-dir .

if [ $# -gt 0 ]; then
    deactivate
fi
