#+LaTeX_HEADER:\usepackage[margin=2cm]{geometry}
#+LaTeX_HEADER:\usepackage{enumitem}
#+LaTeX_HEADER:\usepackage{tikz}
#+LATEX:\setitemize{noitemsep,topsep=0pt,parsep=0pt,partopsep=0pt}
#+LATEX:\lstdefinelanguage{javascript}{basicstyle=\scriptsize\ttfamily,numbers=left,numberstyle=\scriptsize,stepnumber=1,showstringspaces=false,breaklines=true,frame=lines}
#+OPTIONS: toc:nil ^:nil num:nil

#+TITLE: TIPSY configuration guide

TIPSY relies on a high-level main configuration file to perform reliable
and reproducible benchmarks. The key to the flexibility of TIPSY is that
this configuration allows to define a wide range of different tests, from
stability tests to scalability and robustness measurements, using minimal
configuration on the side of the user.

A sample configuration for TIPSY is given below.

#+BEGIN_SRC javascript
{
    "benchmark": [
        {
            "id": "test1",
            "scale": "outer",
            "pipeline": {
		"core": 1,
		"name": "mgw",
                "user": [4,8],
                "bst": 1,
                "server": 2,
                "rate-limit": 10000,
                "nhop": 4,
                "fakedrop": false,
                "fluct-user": 0,
                "handover": 0,
                "fluct-server": 4
            },
            "traffic": {
                "pkt-num": 10000,
                "pkt-size": [64, 128],
                "dir": ["uplink", "downlink", "bidir"]
            }
        }
    ],
    "environment": {
        "sut": {
            "type": "bess"
        },
        "tester": {
            "type": "moongen",
            "test-time": 30
        }
    },
    "visualize": []
}
#+END_SRC

The general rule is that when a configuration parameter is omitted, TIPSY
chooses a sane built-in default.

* The =benchmark= section

The configuration defines a main =benchmark= section that defines a list of
benchmarks to be run. This allows to request multiple TIPSY benchmarks in a
single configuration.

Each benchmark in turn defines the following subsections:

- an unnamed "general" section that gives the overall settings for the
  benchmark, like name, scaling mode, etc.
- =pipeline=: pipeline-specific settings
- =traffic=: traffic generator settings

* The =pipeline= section

Pipeline specific settings. The =pipeline= section has a mandatory =name=
parameter that defines the name for the pipeline to be configured for the
benchmark. The =core= parameter defines the number of CPU
cores/workers. For other specific settings consult the docs and JSON schema
of the individual pipelines.

* The =traffic= section

Parameters for the traffic trace that will be fed to the pipeline by the
Tester. This section might contain the below parameters.

- =pkt-size=: packet size [byte]
- =pkt-num=: number of packets
- =dir=:
  - =uplink=: evaluate the upstream datapath
  - =downlink=: evaluate the downstream datapath
  - =bidir=: run test in both directions
- =thread=: number of requested processing CPU threads. 0 means all of the
  available cores.
- =ascii=: dump generated packets in human readable ASCII form

* The =environment= section

Parameters of the testing environment, configuration of the SUT and of the
Tester. We suppose these parameters are static during the benchmarks.

- =sut=: SUT settings
- =tester=: Tester settings

* The =tester= section

Parameters for the Tester, among others, the traffic generator backend to
be used for insert the traffic trace into the SUT and other Tester specific
settings.

- =type=: packet generator for the Tester (=moongen= or =scapy=)
- =test-time=: runtime in seconds
- =moongen-cmd=: absolute path of the MoonGen executable
- =uplink_port= and =downlink_port=: port name ('eth1') or pci addr for
  DPDK ('0000:0b:00.0') or DPDK port number (in case of moongen, e.g., '0').
- =setup_script=: absolute path of your custom Tester setup script. Useful
  for e.g. automating DPDK interface configuration.
- =teardown_script=: absolute path of your custom Tester teardown script

* The =sut= section

Settings for the System-Under-Test (SUT).

- =type=: SUT implementation (=bess= or =ovs=)
- =hostname=: hostname that can be used to ssh into SUT without a password
  as 'ssh hostname'.  Edit ~/.ssh/config for more complicated scenarios.
  See man page: ssh_config (5)
- =bess-dir=: a directory on SUT in which BESS is installed
- =tipsy-dir=: a directory on SUT in which TIPSY is installed
- =uplink_port= and =downlink_port=: port name ('eth1') or pci addr for
  DPDK ('0000:0b:00.0') or DPDK port number (in case of moongen, e.g., '0').
- =setup_script=: absolute path of your custom SUT setup script. This
  script is run when measurements starts with a new SUT implementation.
- =teardown_script=: absolute path of your custom SUT teardown script. This
  script is run when measurements are done with a SUT implementation.
