# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.define "Tester" do |t|
    t.vm.hostname = "Tester"
    t.vm.network "private_network", ip: "192.168.50.11",
        virtualbox__intnet: true, adapter: 2
    t.vm.network "private_network", ip: "192.168.50.12",
        virtualbox__intnet: true, adapter: 3
    t.vm.network "private_network", ip: "192.168.50.13",
        virtualbox__intnet: true, adapter: 4
    t.vm.network "forwarded_port", guest: 2001, host: 12001,
        guest_ip: "192.168.50.11", autocorrect: true,
        protocol: "udp", id: "uplink"
    t.vm.network "forwarded_port", guest: 2002, host: 12002,
        guest_ip: "192.168.50.12", autocorrect: true,
        protocol: "udp", id: "downlink"
    t.vm.network "forwarded_port", guest: 2003, host: 12003,
        guest_ip: "192.168.50.13", autocorrect: true,
        protocol: "udp", id: "management"
    t.vm.provider "virtualbox" do |vb|
      vb.name = "Tester"
      vb.memory = 4096
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--nic1", "nat"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype3", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype4", "virtio"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
    end
    t.vm.provision "shell",
      path: "install.sh"
  end
end
