# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.define "Tester" do |t|
    t.vm.hostname = "Tester"
    t.vm.network "private_network", ip: "192.168.51.2",
        virtualbox__intnet: "tu2sd", adapter: 2
    t.vm.network "private_network", ip: "192.168.52.2",
        virtualbox__intnet: "td2su", adapter: 3
    t.vm.network "private_network", ip: "192.168.53.2",
        virtualbox__intnet: "mgmnt", adapter: 4
    t.vm.provider "virtualbox" do |vb|
      vb.name = "Tester"
      vb.memory = 4096
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--nic1", "nat"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype3", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype4", "virtio"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
    end
    config.vm.synced_folder ".", "/vagrant"
    config.vm.synced_folder "../..", "/opt/tipsy"
    t.vm.provision "file",
      source: "../ssh/id_rsa",
      destination: "~/.ssh/id_rsa"
    t.vm.provision "shell",
      path: "install.sh"
    t.vm.provision "shell",
      path: "dpdk-init.sh",
      run: "always"
  end
end
