#!/usr/bin/env python3

# TIPSY: Telco pIPeline benchmarking SYstem
#
# Copyright (C) 2018 by its authors (See AUTHORS)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

import sys
import argparse
import json

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

parser = argparse.ArgumentParser()
parser.description = "Extract a proprety from a json object"
parser.add_argument('filename', type=argparse.FileType('r'))
parser.add_argument('pname', metavar='property-name', type=str)
args = parser.parse_args()

obj = json.load(args.filename)
try:
    obj = obj[args.pname]
except KeyError as e:
    eprint(e)
    eprint('Available properties: %s', obj.keys())
    exit(-1)

print(json.dumps(obj, indent=2, sort_keys=True))
